Args <- commandArgs()
library(ggplot2)
library(scales)
Raw_Data <- read.table(Args[6],sep="\t",header=FALSE,stringsAsFactors=FALSE)
colnames(Raw_Data) <- c("depth","kmer")
p <- ggplot(Raw_Data, aes(x=depth,y=kmer))+geom_point()
final <- p + scale_x_continuous(labels = comma) + scale_y_continuous(labels = comma)
ggsave(filename='kmer_depth_plot.jpg',plot=final)
ggsave(filename='kmer_depth_plot.pdf',plot=final)
ggsave(filename='kmer_depth_plot.png',plot=final)
